services:
  - type: web
    name: akashee-draw-intelligence-backend
    env: python
    root: server
    buildCommand: pip install -r ../requirements.txt
    preStartCommand: pip list
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    env:
      - key: RENDER_PYTHON_USE_POETRY
        value: "false"
    plan: free
    buildFilter:
      paths:
        - server/**

  - type: web
    name: akashee-draw-intelligence-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    buildFilter:
      paths:
        - client/**
